name: 'Create ROBOT diffs on Pull requests'

on:
  # Triggers the workflow on pull request events for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create_diff_file:
    runs-on: ubuntu-latest
    steps:
      # Checks-out the branch being merged into master in the root directory
      # The ontology obo file path will be: src/ontology/fypo-edit.owl
      - uses: Bhacaz/checkout-files@v2
        with:
          files: .github/workflows/diff.yml
          branch: ${{ github.head_ref}}
        run: echo hello;
      - name: Run dummy
        run: cat .github/workflows/diff.yml > dummy.txt;
      - name: Post comment
        env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: NejcZdovc/comment-pr@v1.1.1
        with:
          file: "../../dummy.txt"
          identifier: "HELLO"